import os
from pathlib import Path

def generate_architect_reference():
    root = "/home/gsmash/Documents/Devops"
    
    content = [
        "# 🚀 The DevOps Master Logic | Senior SRE Reference",
        "> **Architect-Grade Knowledge Base | Unified Workflow Index**",
        "\n---",
        "## [00] Metadata | System Governance",
        "| Component | Standard/Version | Health |",
        "| :--- | :--- | :--- |",
        "| **Naming** | Lowercase Kebab-Case | ✅ Stable |",
        "| **IaC** | Terraform 1.6+ | ✅ Audited |",
        "| **Containers** | Docker Engine 24.0+ | ✅ Verified |",
        "| **Last Audit** | 2026-02-06 | SRE Certified |",
        "\n---",
        
        "## [01] Networking | Connectivity | SS/IP",
        "**Keywords:** #networking #dns #connectivity #troubleshooting",
        "\n| Service | Action | Tool | Command |",
        "| :--- | :--- | :--- | :--- |",
        "| DNS | Query Short | dig | `dig +short @8.8.8.8 google.com` |",
        "| Traffic | Listen | ss | `ss -tulpn` |",
        "| Routing | View Trace | traceroute | `traceroute -n 8.8.8.8` |",
        "| API | Debug Headers| curl | `curl -IL https://api.service.com` |",
        "\n> [!TIP] Always use `ip -c addr` for colored interface status to quickly identify bridge network issues during cluster debugging.",
        "\n---",

        "## [02] Compute & Cloud | AWS/Azure/GCP",
        "**Keywords:** #aws #cloud #compute #iam #S3",
        "\n| Service | Action | Tool | Command |",
        "| :--- | :--- | :--- | :--- |",
        "| EC2 | List Running | aws cli | `aws ec2 describe-instances --filters \"Name=instance-state-name,Values=running\"` |",
        "| S3 | Audit Size | aws cli | `aws s3 ls s3://bucket --recursive --summarize` |",
        "| IAM | Check Access | aws cli | `aws sts get-caller-identity` |",
        "\n> [!CAUTION] Never delete cloud resources without first generating a `terraform plan` to verify external dependencies.",
        "\n---",

        "## [03] Automation | Terraform | HCL",
        "**Keywords:** #terraform #iac #ansible #automation",
        "\n| Service | Action | Tool | Command |",
        "| :--- | :--- | :--- | :--- |",
        "| Init | Provider Sync | terraform | `terraform init -upgrade` |",
        "| Apply | Safe Execution | terraform | `terraform apply -auto-approve=false` |",
        "| Ansible | Test Connectivity| ansible | `ansible all -m ping` |",
        "\n> [!IMPORTANT] Use `terraform state list` to confirm resource tracking before manual infrastructure tweaks.",
        "\n---",
        
        "## [04] Search Index | Universal File Map",
        "<details>",
        "<summary>Click to expand Grey-Scale Universal Index (1100+ items)</summary>",
        "\n| Resource | Tier | Path |",
        "| :--- | :--- | :--- |"
    ]
    
    # Generate the automated index
    all_md = []
    for dirpath, dirnames, filenames in os.walk(root):
        if any(part.startswith('.') for part in Path(dirpath).parts):
            continue
        for f in filenames:
            if f.endswith('.md') and f not in ['reference.md', '00-REFACTOR-LOG.md', 'readme.md']:
                full_path = Path(dirpath) / f
                rel_path = os.path.relpath(full_path, root)
                tier = rel_path.split('/')[0]
                name = full_path.stem.replace('-', ' ').title()
                all_md.append((name, tier, rel_path))
    
    all_md.sort()
    for name, tier, path in all_md:
        content.append(f"| {name} | {tier} | [{path}]({path}) |")
        
    content.append("</details>\n")
    content.append("---")
    content.append("*Generated by Senior DevOps Documentation Lead - Refactor V2*")

    with open(os.path.join(root, "reference.md"), "w") as f:
        f.write("\n".join(content))

if __name__ == "__main__":
    generate_architect_reference()
    print("✅ Reference.md restored with High-Performance Architecture.")
