# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"

  default_tags {
    tags = {
      Project     = "finishline-infra"
      Environment = "development"
      ManagedBy   = "finishline-infra-team"
      Terraform   = "true"
    }
  }
}
