#!/bin/bash

# ==============================================================================
# Script: repo_structure_analyzer.sh
# Description: Maps project directory structure and generates documentation
# DevOps Context: Onboarding new team members with auto-generated repo guides
# ==============================================================================

set -euo pipefail

# Constants
readonly OUTPUT_FILE="REPOSITORY_STRUCTURE.md"
readonly MAX_DEPTH=3

# Configuration
EXCLUDE_DIRS=(".git" "node_modules" ".terraform" "__pycache__" "venv")

# Logging function
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1: $2"
}

# Check if tree command exists
check_dependencies() {
    if ! command -v tree &> /dev/null; then
        log "WARN" "tree command not found. Using find as fallback."
        return 1
    fi
    return 0
}

# Generate structure using tree
generate_with_tree() {
    local target_dir="${1:-.}"
    
    log "INFO" "Generating structure using tree command..."
    
    local exclude_pattern=""
    for dir in "${EXCLUDE_DIRS[@]}"; do
        exclude_pattern="$exclude_pattern -I $dir"
    done
    
    tree -L "$MAX_DEPTH" $exclude_pattern "$target_dir" > "$OUTPUT_FILE"
}

# Generate structure using find (fallback)
generate_with_find() {
    local target_dir="${1:-.}"
    
    log "INFO" "Generating structure using find command..."
    
    {
        echo "# Repository Structure"
        echo ""
        echo "Generated on: $(date +'%Y-%m-%d %H:%M:%S')"
        echo ""
        echo "\`\`\`"
        find "$target_dir" -maxdepth "$MAX_DEPTH" -type d \
            $(printf "! -path '*/%s/*' " "${EXCLUDE_DIRS[@]}") \
            | sort | sed 's|[^/]*/| |g'
        echo "\`\`\`"
    } > "$OUTPUT_FILE"
}

# Add documentation header
add_documentation() {
    local temp_file="${OUTPUT_FILE}.tmp"
    
    {
        echo "# 📁 Repository Structure Documentation"
        echo ""
        echo "> Auto-generated on: $(date +'%Y-%m-%d %H:%M:%S')"
        echo ""
        echo "## Directory Tree"
        echo ""
        cat "$OUTPUT_FILE"
        echo ""
        echo "## Key Directories"
        echo ""
        echo "| Directory | Purpose |"
        echo "|-----------|---------|"
        echo "| \`src/\` | Source code |"
        echo "| \`scripts/\` | Automation scripts |"
        echo "| \`docs/\` | Documentation |"
        echo "| \`tests/\` | Test suites |"
        echo ""
        echo "---"
        echo "*Generated by: \`boilerplate_repo_structure_analyzer.sh\`*"
    } > "$temp_file"
    
    mv "$temp_file" "$OUTPUT_FILE"
}

# Main function
main() {
    local target_dir="${1:-.}"
    
    log "INFO" "Analyzing repository structure: $target_dir"
    
    if check_dependencies; then
        generate_with_tree "$target_dir"
    else
        generate_with_find "$target_dir"
    fi
    
    add_documentation
    
    log "INFO" "✓ Structure documentation saved to: $OUTPUT_FILE"
    log "INFO" "Review the file and commit it to your repository"
}

main "$@"
