# # EC2 Module - Output
# Generated by terraInfra_1.sh on Mon Mar  9 02:10:52 AM AST 2026

output "instance_id" {
  description = "EC2 instance ID"
  value       = aws_instance.jump_host.id
}

output "instance_public_ip" {
  description = "EC2 instance public IP"
  value       = aws_instance.jump_host.public_ip
}

output "instance_private_ip" {
  description = "EC2 instance private IP"
  value       = aws_instance.jump_host.private_ip
}

output "instance_arn" {
  description = "EC2 instance ARN"
  value       = aws_instance.jump_host.arn
}

