# ------------------------------------
# STATIC INVENTORY (INI Format)
# ------------------------------------

# Ungrouped hosts
localhost ansible_connection=local

# 1. Group by Function
[webservers]
web-01.example.com
web-02.example.com

[dbservers]
db-01.example.com

# 2. Group by Location/Environment
[prod]
web-01.example.com
db-01.example.com

[dev]
web-02.example.com

# 3. Children Groups (Meta-groups)
[all_servers:children]
webservers
dbservers

# 4. Group Variables (Not recommended here, use group_vars/ instead)
[webservers:vars]
http_port=80
