#!/bin/bash

# ==============================================================================
# Script: boilerplate_ssh_config_builder.sh
# Description: Generates SSH config entries for multi-environment access
# DevOps Context: Managing jump hosts and bastion servers
# ==============================================================================

set -euo pipefail

readonly SSH_CONFIG="$HOME/.ssh/config"
readonly SSH_CONFIG_BACKUP="${SSH_CONFIG}.backup.$(date +%Y%m%d_%H%M%S)"

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1: $2"
}

# Backup existing config
backup_config() {
    if [ -f "$SSH_CONFIG" ]; then
        log "INFO" "Backing up existing config..."
        cp "$SSH_CONFIG" "$SSH_CONFIG_BACKUP"
        log "INFO" "✓ Backup saved: $SSH_CONFIG_BACKUP"
    fi
}

# Add host entry
add_host() {
    local host_alias="$1"
    local hostname="$2"
    local user="$3"
    local key_file="$4"
    local port="${5:-22}"
    
    log "INFO" "Adding host: $host_alias"
    
    cat >> "$SSH_CONFIG" <<EOF

# Added by boilerplate_ssh_config_builder.sh on $(date)
Host $host_alias
    HostName $hostname
    User $user
    Port $port
    IdentityFile $key_file
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
EOF
}

# Add jump host configuration
add_jump_host() {
    local alias="$1"
    local jump_host="$2"
    local target_host="$3"
    local user="$4"
    local key="$5"
    
    log "INFO" "Adding jump host configuration: $alias"
    
    cat >> "$SSH_CONFIG" <<EOF

# Jump host configuration
Host $alias
    HostName $target_host
    User $user
    IdentityFile $key
    ProxyJump $jump_host
EOF
}

# Create default configuration
create_default_config() {
    log "INFO" "Creating default SSH configuration..."
    
    # Ensure .ssh directory exists
    mkdir -p "$HOME/.ssh"
    chmod 700 "$HOME/.ssh"
    
    # Create config file
    cat > "$SSH_CONFIG" <<'EOF'
# SSH Configuration
# Generated by boilerplate_ssh_config_builder.sh

# Default settings
Host *
    ServerAliveInterval 60
    ServerAliveCountMax 3
    ConnectTimeout 10
EOF
    
    chmod 600 "$SSH_CONFIG"
    
    # Add sample environments
    add_host "dev-bastion" "bastion.dev.example.com" "ubuntu" "~/.ssh/dev_key.pem"
    add_host "prod-bastion" "bastion.prod.example.com" "ubuntu" "~/.ssh/prod_key.pem"
    add_jump_host "prod-web" "prod-bastion" "10.0.1.50" "ubuntu" "~/.ssh/prod_key.pem"
    
    log "INFO" "✓ Default configuration created"
}

# Main
main() {
    log "INFO" "SSH Config Builder"
    
    backup_config
    
    if [ ! -f "$SSH_CONFIG" ]; then
        create_default_config
    else
        log "WARN" "SSH config exists. Modify manually or remove to regenerate."
    fi
    
    log "INFO" "✓ SSH configuration ready"
    log "INFO" "Test with: ssh dev-bastion"
}

main "$@"
