upstream myapp {
    # flask service name from compose.yaml
    server flask:8080;
}

server {
    listen 443 ssl default_server reuseport;

    server_name api.devopsexample.com;

    # Load the certificates files
    ssl_certificate /etc/letsencrypt/live/api.devopsexample.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.devopsexample.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/api.devopsexample.com/chain.pem;

    # Load the Diffie-Hellman parameters.
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Load the Diffie-Hellman parameters.
    include /etc/letsencrypt/options-ssl-nginx.conf;

    location / {
        proxy_pass http://myapp;
    }
}