# -----------------------------------------------------------------------------
# Name: kustomization.yaml
# Description: A base kustomization file.
# -----------------------------------------------------------------------------

resources:
  - deployment.yaml
  - service.yaml

# 1. Common Labels for all resources
commonLabels:
  app: my-web-app
  tier: frontend

# 2. Name Prefix (Prevents collision)
namePrefix: dev-

# 3. Image Override
images:
  - name: my-app-image
    newName: myproxy/web-app
    newTag: v1.0.1
