# Production Configuration - SSL and NGINX
services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: myapp_config
        target: /etc/nginx/user_conf.d/myapp.conf
    env_file:
      - ./nginx-certbot.env
    networks:
      - public
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - nginx_data:/var/lib/letsencrypt
    depends_on:
      flask:
        condition: service_healthy
        restart: true

  flask:
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/about" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    restart: always

  db-backup:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
      DB_HOST: postgres
    secrets:
      - pg_password
    volumes:
      - ./backups:/backups
    depends_on:
      - postgres
    entrypoint: |
      /bin/sh -c "
      trap 'exit 0' SIGTERM;
      while :; do
        echo \"$(date) - Creating backup...\"
        pg_dump -h $$DB_HOST -U $$POSTGRES_USER $$POSTGRES_DB > /backups/backup_$$(date +%Y%m%d_%H%M%S).sql;
        echo \"$(date) - Backup complete. Sleeping for 24h...\"
        sleep 86400 & wait $${!};
      done;
      "

configs:
  myapp_config:
    file: ./myapp.conf

volumes:
  nginx_secrets:
  nginx_data:
