upstream backend_api {
    server flask:8080;
}

upstream frontend_app {
    server frontend:80;
}

server {
    listen 443 ssl default_server reuseport;

    server_name api.devopsexample.com;

    # Load the certificates files
    ssl_certificate /etc/letsencrypt/live/api.devopsexample.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.devopsexample.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/api.devopsexample.com/chain.pem;

    # Load the Diffie-Hellman parameters.
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Load the Diffie-Hellman parameters.
    include /etc/letsencrypt/options-ssl-nginx.conf;

    location / {
        proxy_pass http://frontend_app;
    }

    location /api/ {
        proxy_pass http://backend_api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}