# # Secret/Iam Module - Output
# Generated by terraInfra_1.sh on Mon Mar  9 02:10:52 AM AST 2026

output "eks_cluster_role_arn" {
  description = "ARN of the EKS cluster IAM role"
  value       = try(aws_iam_role.eks-cluster_role[0].arn, null)
}

output "eks_cluster_role_name" {
  description = "Name of the EKS cluster IAM role"
  value       = try(aws_iam_role.eks-cluster_role[0].name, null)
}

output "eks_nodegroup_role_arn" {
  description = "ARN of the EKS node group IAM role"
  value       = try(aws_iam_role.eks-nodegroup-role[0].arn, null)
}

output "eks_nodegroup_role_name" {
  description = "Name of the EKS node group IAM role"
  value       = try(aws_iam_role.eks-nodegroup-role[0].name, null)
}

output "eks_oidc_provider_arn" {
  description = "ARN of the EKS OIDC identity provider"
  value       = try(aws_iam_openid_connect_provider.eks_oidc_provider[0].arn, null)
}

output "eks_oidc_provider_url" {
  description = "URL of the EKS OIDC identity provider"
  value       = try(aws_iam_openid_connect_provider.eks_oidc_provider[0].url, null)
}

output "eks_oidc_role_arn" {
  description = "ARN of the EKS OIDC IAM role"
  value       = try(aws_iam_role.eks_oidc[0].arn, null)
}

output "eks_oidc_role_name" {
  description = "Name of the EKS OIDC IAM role"
  value       = try(aws_iam_role.eks_oidc[0].name, null)
}

output "eks_oidc_policy_arn" {
  description = "ARN of the EKS OIDC IAM policy"
  value       = try(aws_iam_policy.eks-oidc-policy[0].arn, null)
}

output "eks_nodegroup_instance_profile_arn" {
  description = "ARN of the EKS node group instance profile"
  value       = try(aws_iam_instance_profile.eks_nodegroup_profile[0].arn, null)
}

output "eks_nodegroup_instance_profile_name" {
  description = "Name of the EKS node group instance profile"
  value       = try(aws_iam_instance_profile.eks_nodegroup_profile[0].name, null)
}

