# Base Configuration - Shared infrastructure
services:
  flask:
    image: ganil151/flask:latest
    build:
      context: Flask
      dockerfile: Dockerfile
    env_file:
      - ./Flask/dev.env
    secrets:
      - source: api_key
        target: /run/api_key
      - source: pg_password
        target: /run/pg_password
    depends_on:
      - postgres
    networks:
      - private
      - public

  frontend:
    image: ganil151/frontend:latest
    build:
      context: Frontend
      dockerfile: Dockerfile
    networks:
      - public

  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - pg_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private
      - public

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - private

secrets:
  api_key:
    file: ./Flask/api_key.txt
  pg_password:
    file: ./pg_password.txt

volumes:
  flask-data:
  postgres-data:
  redis_data:


networks:
  public:
    driver: bridge
  private:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/19"
          gateway: "10.0.0.1"
