- hosts: ansible

  tasks:
  - name: create docker image
    command: docker build -t register-1:latest .
    args:
      chdir: /opt/docker

  - name: create tag to push image onto dockerhub
    command: docker tag register-1:latest ganil151/register-1:latest

  - name: push docker image
    command: docker push ganil151/register-1:latest
