
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'python my_build_script.py'
            }
        }
        stage('Test') {
            steps {
                sh 'python my_test_script.py'
            }
        }
        stage('Deploy') {
            steps {
                sh 'python my_deploy_script.py'
            }
        }
    }
}