---
apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: prod
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJnYW5pbDE1MSIsInBhc3N3b3JkIjoiR2FuaWxEb2NrZXIzNzczIiwiZW1haWwiOiJnYW5pbGJhdGlzdHlhbkBnbWFpbC5jb20ifX19Cg==